### ISSUE TITLE
Relation to https://github.com/nim-lang/ui

### ISSUE THREAD

**Issue by dvn0** [genotrance/nimui#1]
I'm assuming you're already aware of https://github.com/nim-lang/ui -- Is this project taking a different approach to the wrapping of libui?

**Comment by genotrance** [comment]
Yes I'm aware of the official wrapper. This effort was prompted by @Araq who wanted to update his wrapper and was curious if nimgen could help speed it up. I just took it on myself and have the Windows version compiling, haven't tested on Linux yet.

Windows version isn't running since I seem to have some DLL issues but I get the same issue with @Araq's official wrapper as well so I am still figuring that out. @jyapayne is also helping with that.

My goal is to have this working and to be compatible with the official wrapper's API. I'll let @Araq decide what to do after things start working properly.

**Comment by dvn0** [comment]
Thanks for the info, it makes sense. Happy to see new development being made in this direction.
